### PR TITLE
add note before archiving repository

### PR DESCRIPTION
**Pull request by dholbach**
Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
cc @morancj - can you review please? couldn't add you as reviewer here

**Review by johnsca — APPROVED** [review]
LGTM.  Thanks for catching this out-of-date repo and cleaning it up. Do you have access to archive the repo?  If not, I can.

**Comment by johnsca** [comment]
Actually, I'll go ahead and merge this and archive the repo.  Please reach out if you need anything different done or other repos attended to.

**Comment by dholbach** [comment]
Please do. Thanks for catching this!

**Pull request merged**
